version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18
    
  build:
    commands:
      - echo "Zipping deployment package..." 
      - zip -r9 ../nodejs.zip .

  post_build:
    commands:
      - echo "Updating lambda Function..."
      - aws lambda update-function-code --function-name prueba-despliegue-remoto  --zip-file fileb://nodejs.zip
      - echo "DONE!!"